config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'

    resources :entries, only: [:index, :create, :new, :destroy]

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :name, message: 'is required.'
  validates_presence_of :message, message: 'is required.'

  default_scope { order(:created_at).reverse_order }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entry = Entry.new
    @entries = Entry.all
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:notice] = 'Your message was saved. Thank you.'
      redirect_to root_path
    else
      @entries = Entry.all
      render :index
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    flash[:notice] = 'The message was deleted.'
    redirect_to root_path
  end

  private

  def entry_params
    params.require(:entry).permit(:name, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/index.html.erb
<% if @entry.errors.any? %>
  <section class="row" id="errors" >
    <ul class="alert alert-danger alert-dismissable text-center" role="alert">
      <% @entry.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>

<section class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3 col-lg-6 well form-area">
    <div class="col-lg-8 col-lg-offset-2">
      <h3>Thanks for stopping by</h3>
      <%= form_for @entry do |f| %>
        <div class="field">
          <%= f.label :message, class: "sr-only" %>
          <%= f.text_area :message, class:"form-control",
                                    placeholder: "Please leave a message",
                                    required: true %>
        </div>
        <div class="field">
          <%= f.label :name, class: "sr-only" %>
          <%= f.text_field :name, class:"form-control",
                                  placeholder: "Tell us your name",
                                  required: true %>
        </div>
        <div class="actions">
          <%= f.submit "Submit", class:"btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </section>

  <section class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3 col-lg-6">
    <% if @entries.empty? %>
      <%= content_tag(:p, 'No messages yet.', class:"panel panel-body") %>
    <% else %>
      <% @entries.each do |entry| %>
        <li class="panel panel-default">
          <div class="panel-heading">
            <%= content_tag(:strong, entry.name) %>
            <%= content_tag(:small, "#{time_ago_in_words(entry.created_at)} ago") %>
            <%= link_to "delete", entry_path(entry),
                              method: :delete,
                              data: { confirm: 'Delete this message?' },
                              class: "pull-right" %>
          </div>
          <div class="panel-body">
            <%= content_tag(:p, entry.message) %>
          </div>
        </li>
      <% end %>
    <% end %>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyGuestbook</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
   <div class="container">
     <div class="navbar-header">
       <span class="navbar-brand">Happy Bear Guestbook</span>
     </div>
   </div>
  </nav>

  <div class="main container">
    <% if alert %>
      <div class="alert alert-danger alert-dismissable text-center" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if notice %>
      <div class="alert alert-success alert-dismissable text-center" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>